### ISSUE TITLE
Boot options change isn't shown with a running VM

### ISSUE THREAD

**Issue by mirh** [virt-manager/virt-manager#103]
I suppose this has something to do with the dialog telling you "these changes will take effect after the next guest shutdown". 
I mean, *of course* this is the case for boot options.. But it gets pretty annoying soon if you happen to see that your edits aren't sticking.

**Comment by crobinso** [comment]
I understand the annoyance, but the UI is meant to show the currently running state of the machine. Yes boot options are a bit weird to handle like that because like you say they only really apply at boot time, but for example if you do a reboot from inside the VM, the old boot setting still apply, so if we updated the UI to show your new settings it wouldn't be accurate for the running VM. So I don't think this should be changed. In virt-manager.git you can always see the next VM boot config via the XML editor window, although it's less friendly to look at

**Comment by mirh** [comment]
Not sure why a certain design choice should be treated as "unchangeable"..
Anyway, can't you still add some tiny icon, highlighting, or whatever else that would point out "something's coming different" while still showing the current settings?
