### ISSUE TITLE
"Listen type" field for Display Spice is unintuitive

### ISSUE THREAD

**Issue by Be-ing** [virt-manager/virt-manager#145]
Continuing discussion from https://bugzilla.redhat.com/show_bug.cgi?id=1867343

I find the "Listen type" field for Display Spice awfully unintuitive. It took me a while of searching the web to understand that SPICE can connect to a VM either locally or over a network. "Listen type" and its options "Address" and "None" do not convey this well. For clearer labels, I propose changing the field name to "VM Location" or "Connection Type" with the options being "Network" and "Local socket".

**Comment by crobinso** [comment]
I agree it doesn't convey the situation well. The situation is complicated though.

Listen type 'none' is not actually a local socket. It is, 'the only way to connect to the graphical console is for libvirt and qemu to coordinate to pass a file descriptor to the client'. Only libvirt using applications like virt-manager and virt-viewer can use this mode.  For people that only use virt-manager on their local machine, that's fine. But if you ever want to use another client, or connect to this VM from a different host, 'none' doesn't work. Compare this with the default listen=127.0.0.1, which actually _is_ a local (network) socket, but also can be used for remote connections if using a libvirt SSH URI. libvirt + qemu also support listening on a local _unix_ socket, which _does_ support SPICE GL, but otherwise doesn't really add compared to 'none'.

It's messy and it's subtle, and there's no single phrase that captures the tradeoffs. In these cases IMO it's better to just stick with libvirt terminology. That way people coming from other places online where this config has been described in libvirt terms may already know what they are looking for. And if people want to know more, they can google about more generalized libvirt/qemu terms then virt-manager specific terms. Going off on our own just causes long term support pain in my experience.

Generally, virt-manager is less aiming to explain confusing concepts to people, and more a front end for libvirt and qemu and their terminology. See [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) for more on that. We try to shave off rough edges of the really common cases. But 3D GL config has a lot of corner cases and isn't really what I would consider supportable at the moment.

So again I agree the UI terminology is not clear. But the reality isn't much clearer TBH. I don't plan to attempt to make this UI any smarter until the Spice GL supportability situation straightens itself out, if ever
