### ISSUE TITLE
RFE: enable more Hyper-V enlightenments by default

### ISSUE THREAD

**Issue by crobinso** [virt-manager/virt-manager#154]
Originally filed here: https://bugzilla.redhat.com/show_bug.cgi?id=1851244

virt-install currently enables hv-time,hv-relaxed,hv-vapic,hv-spinlocks=0x1fff for guests which
support Hyper-V. There are several additional Hyper-V enlightenments supported by
QEMU and libvirt (see https://github.com/qemu/qemu/blob/master/docs/hyperv.txt and
https://libvirt.org/formatdomain.html#elementsFeatures) which could be useful to enable.
In particular, hv_stimer significantly reduces CPU usage when supporting
VMs are paused (see https://lore.kernel.org/kvm/20200625201046.GA179502@kevinolos/).

**Comment by crobinso** [comment]
There's also this RHEL virt-manager bug: https://bugzilla.redhat.com/show_bug.cgi?id=1717616
And this qemu discussion may be relevant: https://www.spinics.net/lists/kvm/msg219359.html

We need to start a discussion with qemu devs to understand what should be enabled by
default, and what things we need to consider to do so, like OS support, host support, etc

**Comment by crobinso** [comment]
Latest plan seems to be to add a convenience option like `hyperv=on` to qemu comand line: https://bugzilla.redhat.com/show_bug.cgi?id=1877467

That let's qemu determine a reasonable default set based on host capabilities. When that lands and is wired up through libvirt that's what virt-manager should use.

**Comment by bryantclcqq** [comment]
Does Hyper-V enlightenments supported in arm/aarch64 machine with windows 11 for arm vm? How to enable them?

**Comment by phrdina** [comment]
So it seems that there will not be `hyperv=on` implemented in libvirt. But there is an alternative where user can specify
```XML
<hyperv mode='passthrough'/>
```
instead of listing every hyper-v feature and this will tell QEMU to enable all hyper-v features available on the current host. The drawback of this feature is that migration to different host will most likely not work. Considering that we already default to host-passthrough for CPU which is essentially the same thing and also makes migration impossible for most cases we might as well use it for windows VMs as default.

**Comment by phrdina** [comment]
After bit more reading at https://www.qemu.org/docs/master/system/i386/hyperv.html and mainly patch not yet merged updating the hyperv document https://lists.nongnu.org/archive/html/qemu-devel/2024-03/msg01111.html we should not use `passthrough` mode in production configuration, instead we need to enable each feature manually.

So to fix this issue we need to implement some logic based on the recommendation from the pending patch.
