### ISSUE TITLE
Bring back network portgroup to UI

### ISSUE THREAD

**Issue by securitym0nkey** [virt-manager/virt-manager#169]
Commit 4c3c53f7738268dbd4508f021567105226bd7aad removed UI for network portgroups. This was a quite useful feature. 

For example: In an open vswitch setup you might use port groups to select the VLAN a guest should reside. While an advanced user can edit XML directly you might have team members who are not that familiar with libvirts XML schema. For those uses the UI feature was helpful.

**Comment by crobinso** [comment]
I agree the feature was useful for some users, but it's an advanced usecase. Your setup sounds quite advanced and niche: users with advanced network knowledge using an advanced network setup that presumably someone else prepared for them and editing the XML is a burden.

But maybe I misunderstood, if you can provide an example network XML you are using and describe the case a bit more it may help me understand. Is this for existing VMs, changing the VLAN, or is it one time setup when the VM is created? Are the users who are making this change the same users who prepared the network XML?

You can sidestep the need for the XML editor for existing VMs by using virt-xml, something like `virt-xml VMNAME --confirm --edit all --network source.portgroup=PORTGROUP`  will change every one of the VMs interfaces to use PORTGROUP

**Comment by umemoni256** [comment]
I would also like to have the portgroup dropdown in the GUI back. I've configured different VLANs on my desktop PC using open vswitch. It's definitly more convenient to change the VLN of VMs using the GUI on a desktop PC than edit the XML everytime I want to change the VLAN.

**Comment by securitym0nkey** [comment]
> I agree the feature was useful for some users, but it's an advanced usecase. Your setup sounds quite advanced and niche: users with advanced network knowledge using an advanced network setup that presumably someone else prepared for them and editing the XML is a burden.
>
> But maybe I misunderstood, if you can provide an example network XML you are using and describe the case a bit more it may help me understand. Is this for existing VMs, changing the VLAN, or is it one time setup when the VM is created? Are the users who are making this change the same users who prepared the network XML?
> 

In my case it's for changing the VLAN as well as for assigning it when creating the VM. 

I'm using this for VLANs on open-vswitch setups like @umemoni256. I know open-vswitch + VLANs is not the most common setup. One might call VLANs 'advanced' for others this is a basic networking thing they use on a daily basis. But being an advanced network user does not mean you are familiar with the XML of libvirt. 
In my case the network XML is created and updated by an ansible playbook i wrote some years ago. So today i'm not that familiar with the XML schema myself. This might be just an inconvenience for me but the bigger issue is that I have also other users/co-admins of the hypervisors who never touched the XML before.

Here an example network XML: https://gist.github.com/securitym0nkey/ce7126f6f3ca958586cfad5e6574f6a3

Maybe there are really good reasons to drop the portgroup select option from UI code base, but i would be super happy to see it coming back.

**Comment by pluggemi** [comment]
@crobinso Yes the portgroup feature was an advanced use case, but so is using openvswitch with virt-manager/libvirt.  And it is those of us who use openvswitch with virt-manager who are most impacted by this change.  The portgroup selection box only appeared when a openvswitch network source was selected, so it only showed to those advanced users, so I don't understand why it was removed from the UI.  

Sure, we can edit the XML to add the portgroup definition, but we shouldn't have to.  This was something that has been present in virt-manager since 1.1.0 and many of us have come to rely on it.

Was this UI option causing other problems?

**Comment by crobinso** [comment]
The UI option itself was not causing problems besides ongoing maintenance load and testing effort, which was small but non-negligible. It was removed as part of a larger effort to define what level of advanced features we want to support in the UI. This was largely to reduce ongoing maintenance burden: code maintenance for one, but more so to simplify the difficult decision whether to accept or rejected features going forward. The UI before was inconsistent with what level of user it was targeting, and we attempted to clarify that, for the long term health of the project and sanity of the maintainers.

IMO portgroups clearly fall on the advanced side of the line. But I am willing to make an exception based on certain factors, like how common the usecase is, how difficult the workaround is without the UI feature, stuff like that.

It seems I misjudged how much portgroups UI is used, I thought it had virtually no users. But this thread and some googling about libvirt openvswitch I see it's a common setup in that world. That doesn't mean it's not an advanced setup (it certainly is by the definition of our [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md)) but it changes the calculus a bit.

But I'm not convinced that despite being an advanced feature we should make an exception for portgroups and revive the UI.

For the XML change, it amounts to changing from

```xml
<network network='network'>
  <source network='test-net'/>
</network>
```

```xml
<network network='network'>
  <source network='test-net' portgroup='vlan-02'/>
</network>
```

So the syntax is very simple. For an existing VM to do the XML editing by hand is more inconvenient than the drop down, but not dealbreakingly so. For a new VM it takes more clicks because you have to go through the 'Customize' wizard but still IMO it's not a huge hurdle IMO.

Also, I _think_ you can get similar UI with multiple virtual network definitions too. You can have multiple networks point at the same bridge with the same openvswitch UUId, and put the <vlan> settings under <network> and not <portgroup>. Name the virtual nets `ovs-vlan1`, `ovs-vlan2` etc with predictable names. Then they will be selectable by default with virt-manager. I did not confirm this myself but from my reading of libvirt code it should work.

FWIW I've not fully made up my mind here and I'm willing to discuss more.

**Comment by pluggemi** [comment]
First, I would like to thank you for being open to the discussion on this.  It is appreciated.  FWIW, I have read through the mailing list thread and the DESIGN.md and for the most part I agree with them.  They nicely align with the philosophy of "sane defaults, able to tweak".

For the port group option, perhaps I should create a use case by painting the scenario that caused me to notice the change. For compute nodes, I have 4 Archlinux based compute nodes running libvirt, openvswitch, and a few other storage related daemons that were built over 2 years ago.  

The openvswitch configuration is a single bridge which has a 10G physical interface performing VLAN trunking connected to the real network devices. The libvirt network configuration contains 6 port groups with 1 VLAN each, and a 7th port group which is a VLAN trunk carrying the 6 available VLANs.  

The management node running virt-manager is an Archlinux desktop. 

These systems were built based on libvirt documentation and RHEL recommendations at that time.  I know that RHEL has switched to recommending Cockpit, but Cockpit has not yet reached feature parity with virt-manager.

When I went to build a new VM and noticed the missing port group selection box, I had to enable XML editing, get the XML configuration details, and look up the correct values in the libvirt config because - quite frankly - I forgot the exact names and capitalization.  It was over 2 years ago when they were set!  I was able to create the VM as desired.  And as you point out, the XML syntax is straight forward - assuming you remember all of your port group names.

The main reason I am advocating for the return of the selection box is because is drastically reduces the risk of a VM build failure due to XML syntax problems or incorrect values being configured due to typos, misspellings, or having to look up the correct names in the libvirt configuration.  The selection box generates valid XML with valid values, reduces troubleshooting effort, and avoids potential future Issues to this Issue tracker that would need to be triaged...

> Also, I think you can get similar UI with multiple virtual network definitions too. You can have multiple networks point at the same bridge with the same openvswitch UUId, and put the settings under and not . Name the virtual nets ovs-vlan1, ovs-vlan2 etc with predictable names. Then they will be selectable by default with virt-manager. I did not confirm this myself but from my reading of libvirt code it should work.

If I am understanding you correctly, then this is the behavior that was working 2.2.1, but is not working in 3.1.0 (see below).  If I am not understanding you correctly, then I would definitely like more details.  The end goal here is the ability to select a VLAN configuration for a VM within the GUI without having to create a bridge port in openvswitch for each VLAN. At the time these servers were built, the recommended way to do this was to use port groups.

Thanks again for the discussion!

<hr>
Here is my ovs-vswitch configuration:
For reference, the interface called "mgmt0" is the management IP for the host itself.  "enp1s0f0" is the 10G nic.
Note that there are not port definitions for each VLAN because they are not needed when using the libvirt openvswitch support and port groups.

```
    Bridge ovsbr0
        Port ovsbr0
            Interface ovsbr0
                type: internal
        Port enp1s0f0
            Interface enp1s0f0
        Port mgmt0
            tag: 1160
            Interface mgmt0
                type: internal
```

This is my libvirt network configuration:
```
<network>
  <name>ovs-network</name>
  <uuid>bc0c534f-c126-48a2-95b6-20ac9db2ad2a</uuid>
  <forward mode='bridge'/>
  <bridge name='ovsbr0'/>
  <virtualport type='openvswitch'/>
  <portgroup name='Server' default='yes'>
    <vlan>
      <tag id='1128'/>
    </vlan>
  </portgroup>
  <portgroup name='Server2'>
    <vlan>
      <tag id='1129'/>
    </vlan>
  </portgroup>
  <portgroup name='Client'>
    <vlan>
      <tag id='1192'/>
    </vlan>
  </portgroup>
  <portgroup name='Backbone'>
    <vlan>
      <tag id='1096'/>
    </vlan>
  </portgroup>
  <portgroup name='Server MGMT'>
    <vlan>
      <tag id='1160'/>
    </vlan>
  </portgroup>
  <portgroup name='Storage01'>
    <vlan>
      <tag id='1161'/>
    </vlan>
  </portgroup>
  <portgroup name='Storage02'>
    <vlan>
      <tag id='1162'/>
    </vlan>
  </portgroup>
  <portgroup name='All VLANs'>
    <vlan trunk='yes'>
      <tag id='1096'/>
      <tag id='1128'/>
      <tag id='1129'/>
      <tag id='1160'/>
      <tag id='1161'/>
      <tag id='1162'/>
      <tag id='1192'/>
    </vlan>
  </portgroup>
</network>
```

This is a screenshot of the network configuration GUI from version 2.2.1:
![image](https://user-images.githubusercontent.com/29031578/99126230-bc280a80-25d3-11eb-9912-a8e98512e9ca.png)

This is a screenshot of the same VM's network configuration GUI for the same VM but using 3.1.0.  Note the missing port group option under the "Network Source" field.
![image](https://user-images.githubusercontent.com/29031578/99126505-47a19b80-25d4-11eb-98f4-061600bc628d.png)

**Comment by tweippert** [comment]
+1 to get it back in the UI

If you need to choose a portgroup on installation tasks it was wonderfull to have it in the GUI, as you choose the ovs network and can choose the vlan also. now this is missing and i don't see a way to edit the xml directly on the "new vm" wizard (or maybe i'm too lazy to find a way)...

**Comment by g-ramirez** [comment]
Another +1 on this as well.  While we can edit the XML, it's a slight hassle to do so.  Not the end of the world, but this was a really neat feature for getting VLAN tagging setup ASAP

**Comment by kab01m** [comment]
+1 on this as well. We use big infrastructure based on KVM/Open vSwitch and virt-manager is the main tool for managing VMs.

**Comment by dhoffend** [comment]
+1 ... I can understand when there's no way to manage portgroups in the network management part of virt-manager ... but the simple dropdown to choose a predefined portgroup is something a non-administrative user is usually able to do, especially in a bigger environment.

**Comment by crobinso** [comment]
Okay, I've re added this upstream now, sorry for the delay. New release will be out in a month or so

**Comment by Akshay-Hegde** [comment]
Oh here is issue, even I was wondering why drop-down is not popping up. Any patch available to enable this drop-down feature ?

**Comment by g-ramirez** [comment]
> Oh here is issue, even I was wondering why drop-down is not popping up. Any patch available to enable this drop-down feature ?

It's working here.  Which version of virt-manager are you using?  Mind sharing your network's XML as well?
