### ISSUE TITLE
Provide a virtio RNG device unconditionally

### ISSUE THREAD

**Issue by bemoody** [virt-manager/virt-manager#193]
When using virt-manager to create a new virtual machine, it prompts me to select the guest operating system, and based on that, tries to select appropriate default hardware.

In particular, it will only create a virtio RNG device if the guest OS (according to libosinfo) knows how to handle it.

(For example, [the osinfo-db package in Debian 10 - which predates the release of RHEL 8 - indicates that RHEL 8 doesn't support any virtio devices](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975272).  However, this problem is not specific to Debian or RHEL.)

It seems to me that, unless there's some complication I don't know of, it should be harmless to provide a virtual RNG even if the operating system doesn't know what to do with it.  And failing to provide this device (especially at first boot) may be risky for security.

```
--- a/virtinst/guest.py
+++ b/virtinst/guest.py
@@ -934,7 +934,6 @@ class Guest(XMLBuilder):
             return
 
         if (self.conn.is_qemu() and
-            self.osinfo.supports_virtiorng(self._extra_drivers) and
             self.conn.support.conn_rng_urandom()):
             dev = DeviceRng(self.conn)
             dev.type = "random"
```

Is there a reason not to do that?

Of course it's possible to override this if necessary, but this is about providing sensible defaults when a VM is first created.

**Comment by crobinso** [comment]
Thanks for the suggestion, it's a reasonable idea. I think there were some linux versions were the device was present in the kernel but not working reliably or not tested enough, but that was a window of time that people are unlikely to be installing anymore.

I am planning to improve the default fallback OS selection in virt-install/virt-manager so that this type of missing device issue is less likely, by advertising linux20XX generic options if your distro isn't in the list. Some discussion here: https://www.redhat.com/archives/virt-tools-list/2020-September/msg00017.html

But I think this change is reasonable too. I'll ask around first to be sure. Probably won't be for a while though

**Comment by bemoody** [comment]
That makes a lot of sense.  Thanks.

**Comment by crobinso** [comment]
It's been a while, but those changes in the linked thread were only just implemented: https://listman.redhat.com/archives/virt-tools-list/2022-February/msg00021.html

At virt-install level we are now requiring a valid libosinfo name for most usage. virt-manager requires selecting an OS for new VMs too. There's still ways to explicitly request 'give me crappy non-virtio defaults' but users need to opt into it explicilty rather than fall into it accidentally as is historically possible.

There will still be problems if osinfo-db is out of date or has bad info, like the example that prompted this bug. However that's something that has generally been steadily improving on upstream osinfo-db side, and in distros. This virt-install/virt-manager changes will make it more clear to distro maintainers that keeping osinfo-db up to date is required for correctly provisioning new VMs.

So with all that said, I don't plan to add the virtiorng device unconditionally, it would essentially paper over bad osinfo-db data, which isn't a sustainable approach. And hopefully it's less necessary these days as distros learn they need to keep osinfo-db up to date.
