### ISSUE TITLE
New VM: Missing PXE option

### ISSUE THREAD

**Issue by volker-raschek** [virt-manager/virt-manager#208]
Hello, I'm missing the option to create and boot new VMs over PXE like the screenshot from the [RHEL docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_host_configuration_and_guest_installation_guide/sect-virtualization_host_configuration_and_guest_installation_guide-guest_installation-installing_guests_with_pxe).

![pxe-boot](https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux-6-Virtualization_Host_Configuration_and_Guest_Installation_Guide-en-US/images/f04fcb62f6fc555254566032d89d91ca/Screenshot-sevenpt3-pic2.png)

I used the PXE boot option for several months ago, but now the option is not any more available. See my screenshot below (german). Has been the PXE boot option removed or does my system not provide all requirements to provide this boot option? 

![Bildschirmfoto vom 2021-01-06 17-19-55](https://user-images.githubusercontent.com/18311012/103792005-6c017d80-5043-11eb-8d91-3bd443813e63.png)

**Infomation**
Distro: Arch Linux

```bash
$ pacman --query virt-manager libvirt libvirt-python
virt-manager 3.2.0-1
libvirt 6.8.0-3
libvirt-python 1:6.4.0-3
```

Volker

**Comment by crobinso** [comment]
Those screenshots are out of date, the explicit PXE option has been removed in virt-manager 3.0.0+. You can get the same behavior by choosing 'Manual install', then on the final page of the wizard, select 'Customize before install', and change the boot device to Network

**Comment by g-v-egidy** [comment]
I'm also missing the pxe install option since I migrated to virt-manager 3.0 (when updating to a new Fedora).

Using the manual install has the downside that after the install is done, you have to shut down the machine in the right moment and switch the boot media over to disk. When using the regular automatic install, the first reboot is detected and the boot media switched over automatically.

Is there a special reason why this option was removed? Would you take patches bringing it back?

**Comment by crobinso** [comment]
PXE was dropped as part of adjusting the UI to fit (DESIGN.md)[https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md]. PXE is an advanced feature that requires external network setup to use, and it's achievable with some extra clicks as you describe. I do not plan to re-add it to the UI.

If you do PXE installs frequently enough that this is a particular annoyance, I recommend you use `virt-install`. You can hide all the options in a wrapper shell script if you want. Kicking off a PXE install with os suggested defaults can (basically what virt-manager will give you) is `virt-install --osinfo fedora34 --pxe`

**Comment by g-v-egidy** [comment]
Thanks for your quick answer.

> PXE was dropped as part of adjusting the UI to fit (DESIGN.md)[https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md]. PXE is an advanced feature that requires external network setup to use, and it's achievable with some extra clicks as you describe. I do not plan to re-add it to the UI.

Setting up a PXE server is a small admin task to setup up once. But it then quickly pays off, so I guess having it in a business or lab environment is quite common. Dealing with install media for real hardware is such a nuisance that you really want it for that. If it is already there, it makes sense to use it for VMs too. So I don't consider it that much advanced.

> If you do PXE installs frequently enough that this is a particular annoyance, I recommend you use `virt-install`. You can hide all the options in a wrapper shell script if you want. Kicking off a PXE install with os suggested defaults can (basically what virt-manager will give you) is `virt-install --osinfo fedora34 --pxe`

That won't help me, as I have to tweak the required virtual hardware in nearly all cases, like selecting a specific storage volume or a specific kind of network setup to do my work. So I'd have to fall back to the manual method.

How about adding it to the "Network Install" main menu? This will keep the main menu brief. In the install URL menu you could then add a checkbox to use PXE instead of a URL.

**Comment by crobinso** [comment]
If you select a boot order of disk first, then PXE, does it 'just work' how you expect? First boot does not find a bootable disk, so falls back to PXE. Second boot the disk is now bootable, and it's the first boot entry, so it will boot into the OS. (in theory)
