### ISSUE TITLE
Chipset and BIOS are selectable only while creating a new vm

### ISSUE THREAD

**Issue by tps800** [virt-manager/virt-manager#215]
**Distro**: xUbuntu 20.10, virt-manager from git checkout
Chipset and BIOS are selectable only while creating a new vm. If vm is created once chipset and bios remain fixed.
They should be selectable after creation of the virtual machine, as there are ways to switch booting with legacy or uefi in real hardware too.
Switching may lead to unbootable systems, but it might be intended: testing if system setup works with both – bios and uefi systems.

**Comment by phrdina** [comment]
Hi, thanks for the report. This is intentional and for now there are no plans to change it. The BIOS should not be that difficult but changing chipset requires a lot of other modifications for the whole VM. Currently we supports two chipsets, i440fx and Q35 where they are completely different. For example i440fx supports PCI but Q35 uses PCIe by default and the topology and PCI address configuration would require a lot of changes.

If the change is really needed users can use different VMs for test purposes or change the XML manually.
