### ISSUE TITLE
Allow to select a physical Disk as booting device

### ISSUE THREAD

**Issue by Mannshoch** [virt-manager/virt-manager#218]
![grafik](https://user-images.githubusercontent.com/7795891/105830432-ca2bdb80-5fc5-11eb-8372-5c2afa66de0f.png)

**Comment by phrdina** [comment]
Hi, thanks for the idea but I don't think this is a good fit in virt-manager GUI for several reasons.

Firstly the first page of VM creation lists installation option, so there shouldn't be option that selects a disk for VM, that is done in following steps.

Another reason is that this would not work for remote connection where we talk only to libvirt.

And finally it can be already done in the disk creation step where you can pick "Select or create custom storage" and simply type `/dev/sda` into that field. This way it will work even for remote connection because you would type in a path on the remote host.

**Comment by crobinso** [comment]
Yeah this is already available like Pavel says. Select Manual Install, then enter /dev/.... into the storage field on page 4.

**Comment by Mannshoch** [comment]
Thanks now it wokrs for me. Would it be an Idea to create a new Issue and ask for enhancing the UI description?
