### ISSUE TITLE
Cannot wake a VM from Sleep mode (pmsuspended)

### ISSUE THREAD

**Issue by t9999clint** [virt-manager/virt-manager#258]
Not sure if this counts as a bug or a feature request, but it's damn annoying...
I have a windows 10 vm with GPU passthough that whenever if goes to sleep I can't wake it up from the Virt-Manager gui.
I have to wake it up using the `virsh dompmwakeup <VM-NAME>` command.

Can you guys add a button or something for this so I don't have to drop to a terminal everytime I need to wake up a VM?

I could disable sleep mode, but I like having my VM's go to sleep so I can save power with cpu/gpu cycles. It also means I don't have to worry about the added attack surface of a always on Windows VM.
**Distro**: NixOS

**Comment by crobinso** [comment]
Thanks for the suggestion. For non-gpu passthrough guests you can wake up the VM just by typing into the graphical console, but that obviously doesn't work for your case. I think this setup is obscure enough that adding explicit UI support for it is not worth the effort and maintance burden, sorry.

You could add a shell alias in your PATH called 'wakevm' or something, then alt+f2 'wakevm' to get what you want.

**Comment by t9999clint** [comment]
I had a bit more time to think about this. And I have something to suggest, if you still feel like it's not worth bothering with than that's fine. Just give me a sec to explain...

my recommendation, in order to minimize needless clutter to the UI would be by modifying the functionality of the run button to wake the VM if it's in a suspended status instead of greying it's self out like it does now. Should only require a few lines of code to add and should be fairly minimal to debug. I am no programmer though, so I admit that I could be very wrong about that.

While I agree that my use case is pretty uncommon, I can still make the argument that this feature could still benefit normal users. By adding this functionality someone can wake a suspended vm simply by rightclicking on it and clicking Run.

This would be much easier than opening up the VM, navigating to the console, have it grab your mouse and keyboard, and typing frantically in a vague attempt to awake the VM. Also much quicker to do with a Virt-Manager instance that's connected to a remote server over ssh or something similar.

Regardless of your decision on this, thanks for taking your time to read this and consider this feature request.

**Comment by crobinso** [comment]
It's a good idea and I was looking into it a bit before I posted my last comment. There's already a precedent for it, grep around for 'change_run_text' lines that contain `has_managed_save()` calls. Basically when the VM is 'saved', we change the run() text to say 'Restore' in a few places. startup() in virtManager/object/domain.py would need to be changed to run the correct call if the VM is in pmsuspended state. is_runable() would need to return True if domain is in pmsuspended state. That would probably cover most of it.

If someone showed up with a patch for that I would consider it. But the problem is that it adds explicit UI support and code paths for a very niche usecase that, at best, saves the user some fairly mild typing. Making changes like this to virt-manager doesn't scale and contributes to a bad precedent IMO. I've stripped a lot of those things out of virt-manager over the past few years, wrote [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md), and I'm trying to stick to it.

**Comment by mabra** [comment]
> Thanks for the suggestion. For non-gpu passthrough guests you can wake up the VM just by typing into the graphical console, but that obviously doesn't work for your case. I think this setup is obscure enough that adding explicit UI support for it is not worth the effort and maintance burden, sorry.
> 
> You could add a shell alias in your PATH called 'wakevm' or something, then alt+f2 'wakevm' to get what you want.

But the UI is mixing things - that probably more worse.
When my guest dies today - just froozen - I started searching and foung
>you can wake up the guest by clicking the "shutdown" button in virt-manager. Basically the guest needs an ACPI interrupt to wake from s2idle, and that's injected by a powerdown request. Please refer to [bug 1223541](https://bugzilla.redhat.com/show_bug.cgi?id=1223541)<
I followed the advice - clicking the shutdown botton, but the guest shuts down.
In reality, there is no shutdown button, it's a menue, with 5 submenues, one of them named shutdown .... this all is to understand of one of the usual management options (like you will find even in the guest management oprion and so VERY different from a power button of a usual computer, which is hardware.
After I lost my work, I found that the behavior has an even so bad pendent in systemd: The XQL driver died and systemd set the system in a sleep-state (different from suspend/hivernate), where "a real powerbotton" could have helped.
Just my two cents.
