### ISSUE TITLE
Mouse Speed / Acceleration is changed on Windows by Virt-Viewer

### ISSUE THREAD

**Issue by swinokur** [virt-manager/virt-manager#261]
Hello,

I'm using Virt-Viewer 9.0.257 on Windows 7 to view virtual machines running on a proxmox system.

I fairly regularly see cases where something happens related to virt-viewer, where the Windows system mouse speed & acceleration are getting changed. (So my "fast" mouse in windows is suddenly a "slow" mouse)

This seems to happen when virt-viewer is in the mode where the mouse is "captured" and then released. 

I've done some searching to try to see if this has already been reported and/or if there is a workaround and haven't been able to find anything.

Please let me know if there's more information / diagnostics / things to try.

thanks!

**Comment by crobinso** [comment]
Thanks for the report, but virt-viewer is a separate project, hosted here: https://gitlab.com/virt-viewer/virt-viewer

But to me that sounds like a guest driver issue. Are you using qxl video with qxl drivers inside the VM? See if switching to plain vga device also reproduces the issue. If not, it's probably a qxl windows driver problem. But if that's the case you are out of luck because there aren't any new versions coming for windows 7 IIRC.
