### ISSUE TITLE
[Feature Request] That you can set a schedule for automatic snapshots for a specific vm

### ISSUE THREAD

**Issue by Toadfield** [virt-manager/virt-manager#272]
I want to be able to set a specific schedule in which an automatic snapshot for a specific vm gets created.

**Comment by crobinso** [comment]
This is not something that can be implemented in virt-manager since there's no guarantee the app is running all the time, and IMO it's outside the scope of virt-manager anywas per [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md).

Probably isn't too much work to implement this with a script that `cron` invokes
