### ISSUE TITLE
after system update virt-manager is frequently crashing

### ISSUE THREAD

**Issue by Mlocik97** [virt-manager/virt-manager#317]
**Distro**: Ubuntu 20.04

After system update when I open VM in virt-manager, it randomly close windows... VM is still running, but windows is closed and I again need to open virt-manager. It happens on input.

**Comment by jwatt** [comment]
I was getting this constantly after upgrading from Fedora 34 to 35, and every time when a system modal dialog/prompt opened in the Windows guest. Sometimes virt-manager would just crash, and sometimes it would hang and I'd get a dialog prompt:

    "Virtual Machine Manager" is not responding.
    You may choose to wait a short while for it to continue or
    force the application to quite entirely.

And in journalctl just:

    libvirtd[1555]: Internal error: connection closed due to keepalive timeout

After fighting through many crashes/hangs in order to update to the [latest stable WinFSP](https://github.com/billziss-gh/winfsp/releases) release, run `virtio-win-guest-tools.exe` from the [latest virtio-win.iso](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/), and getting Windows fully up to date, the issue seems to have gone.

Given we're on very different versions of Linux (kernel in particular) the underlying issue in your case is likely to be different, but maybe give the above updates a shot if you haven't already.

**Comment by Mlocik97** [comment]
same journalctl but I have Linux in VM, so `virtio-win-guest-tools.exe` is useless for me.

**Comment by Mlocik97** [comment]
I tested it for some time, and it seems it crash when openGL is enabled. :worried:

**Comment by crobinso** [comment]
If it's OpenGL related, it's highly likely somewhere else in the stack: kernel, qemu, virglrenderer, spice-gtk, something like that. You can isolate virt-manager by seeing if this reproduces in virt-viewer or not, there's some steps here: https://github.com/virt-manager/virt-manager/wiki/Debugging-VM-graphical-display-issues

**Comment by Mlocik97** [comment]
I solved it,... when OpenGL enabled, I needed to write:

```xml
<qemu:env name="MESA_LOADER_DRIVER_OVERRIDE" value="iris"/>
```

to libvirt config
