### ISSUE TITLE
Start Placing VM Configurations in the User Home Directory

### ISSUE THREAD

**Issue by Lonniebiz** [virt-manager/virt-manager#330]
Why does Virt-Manager place virtual machine configurations apart from the virtual hard drive in places like /var/lib/libvirt/images/ ?

Instead I was expecting there to be a place in my home folder for saving those files.

You see, I backup my home folder, but I had no clue that I also needed to back up this var folder location in order to not lose the configurations of my virtual machines in a failure.

I have a virtual machine whose disk file was saved to another hard drive. My main drive failed, so I'm currently trying to set everything up from a backup. Unfortunately, I have no backup of these configuration files that weren't saved on the same hard drive as where the virtual disks were saved.

I'm sure I can create the same configuration again, but I bet it is going to cause problems on the proprietary virtual machines I run, which probably expect MAC addresses of virtual network cards (and no telling what else) to be exactly the same as they were before or else it will no longer consider my registration/license valid.

The user interface of VMM offers no settings to change where this stuff is saved. This is the closest thing I could find:
![NewVirt](https://user-images.githubusercontent.com/151919/144337176-739787e6-9d9b-41b1-bfe3-b1365454c8cb.png)

If there's one thing I need from this UI, it is the ability to change this default location where it saves things. I don't want to have to worry about doing this on a per VM basis. I'd like the ability to set this up once, and know that any of the VMs I create are going to backed up 100%. Ideally, when you install a virtual machine, everything should be in one folder and not spread out between hard drives.

**Comment by crobinso** [comment]
Thanks for the report but unfortunately there's lots of subtle historical reasons why we don't store images in $HOME by default. What you probably want is the libvirt `qemu:///session` URI instead of what virt-manager `qemu:///system` which virt-manager uses by default. You can read about the difference here: https://blog.wikichoon.com/2016/01/qemusystem-vs-qemusession.html

If you just want to change the default storage location, there's some steps here: https://blog.wikichoon.com/2014/07/virt-manager-changing-default-storage.html

gnome boxes is a tool that is designed to work like you expect, you may want to give that a shot.

**Comment by Lonniebiz** [comment]
Thanks for the reply. I'll read the links you've provided.
