### ISSUE TITLE
Add VM to groups

### ISSUE THREAD

**Issue by x09** [virt-manager/virt-manager#363]
Hi, I have 15-20 VMs and virt-manager displays them as a simple list. This is terrible and very inconvenient. 
VMs for different tasks and some are logically linked to each other for parallel work.
Or add different columns for sorting VMs.

It would be convenient if there was a grouping of virtual machines into groups (like as VirtualBox)

I have read the  DESIGN.md and I think it needs to be revised for the modern world.

**Comment by crobinso** [comment]
Nothing has changed since the last time someone requested this. We've decided it's outside the UI scope of virt-manager. You may now like it but that doesn't change the decision.

You can get a minimal form of alphabetic grouping by using the VM 'title' field, without actually changing the VM name like virsh uses. You can use ctrl+f string prefix matching to speed up finding some VMs in the list. But that's the extent of the organizational abilities we plan to provide.
