### ISSUE TITLE
Support for hostfwd in usermode networking

### ISSUE THREAD

**Issue by voidplayer** [virt-manager/virt-manager#365]
**Distro**: debian, redhat, fedora

Qemu has an easy way to redirect ports [in an user network](https://wiki.qemu.org/Documentation/Networking#How_to_get_SSH_access_to_a_guest)

Being able to do it from virt-manager would be extremely convenient for intermediate user because is the only way to connect to a machine that runs user space. Im still trying to figure it out the xml, since [im not sure it is supported](https://libvirt.org/formatdomain.html#userspace-slirp-stack)

I read [your simplification of the networking](https://blog.wikichoon.com/2019/04/host-network-interfaces-panel-removed.html) and i hope this doesnt include port redirection :)

I think is possible to do it by [adding qemu options](https://unix.stackexchange.com/a/519067), but its not possible from virt-manager because it removes the first line <domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'> when you click apply

Thanks for reading!

**Comment by crobinso** [comment]
Thanks for the suggestion, but you're right that libvirt does not support hostfwd XML so that is the main blocker if we wanted to add it to the UI. But I think even if libvirt supported it we would not add it to the UI. usermode networking is only even advertised in the UI for qemu:///session which the user needs to go out of their way to use with virt-manager, and the networking mode is discouraged compared to whitelisting virbr0 with qemu-bridge-helper and entering it as a manual bridge path in the UI, which gets you similar networking connectivity as default qemu:///system VMs.

As for the qemu options issue, I just tried it in the XML editor and it worked for me. Can you try again with virt-manager.git? if it's not working, paste the full XML you wrote before you click the Apply button and I'll see if I can reproduce.

**Comment by voidplayer** [comment]
It worked after using the whole configuration instead of just a part :)

Not sure what is so bad about qemu:///session to not be considered tho

I [opened a bug in libvirt](https://gitlab.com/libvirt/libvirt/-/issues/285)

I think is worth having an easy way to redirect a port

Thanks for your work and the fast reply and ! :)

**Comment by crobinso** [comment]
Libvirt hasn't added hostfwd support yet. When it does we would add support to virt-install/virt-xml but probably not the virt-manager UI since we don't really advertise usermode there much.
