### ISSUE TITLE
"Failed to initialize EGL render node for SPICE GL" when using NVIDIA proprietary driver

### ISSUE THREAD

**Issue by raffaem** [virt-manager/virt-manager#396]
Distro: Fedora Workstation 36
Virtual Machine Manager 4.0.0

I have a Windows 11 guest.

I use a Spice Display with it.

If I enable OpenGL and select my NVIDIA card, I get the following error:

```
Error starting domain: internal error: process exited while connecting to monitor: 2022-05-27T06:33:11.169237Z qemu-system-x86_64: egl: eglInitialize failed
2022-05-27T06:33:11.169319Z qemu-system-x86_64: Failed to initialize EGL render node for SPICE GL

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib64/python3.10/site-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2022-05-27T06:33:11.169237Z qemu-system-x86_64: egl: eglInitialize failed
2022-05-27T06:33:11.169319Z qemu-system-x86_64: Failed to initialize EGL render node for SPICE GL
```

If I choose the Intel integrated graphics, everything runs fine.

I have the proprietary NVIDIA drivers version 510.68.02.

**Comment by crobinso** [comment]
Thanks for the report but this is outside the scope of virt-manager, spice gl and virgl have lots of tight dependencies on bits of the graphics stack and host kernel and things are constantly breaking and unbreaking as packages update. Maybe check your `/var/log/libvirt/qemu/VMNAME.log` file and see if there's more error messages, it could explain it.

There's some mention of broken virgl + nvidia here: https://gitlab.freedesktop.org/virgl/virglrenderer/-/issues/253

But I'm closing this since it's unlikely there's anything we can do on virt-manager side

**Comment by raffaem** [comment]
I have writte to QEMU ML. Then I will report it as a QEMU bug I guess.

How can I have the full QEMU command line called by virt-manager upon starting the VM?

**Comment by HH756** [comment]
@raffaem did you ever find an easy solution? I also have Nvidia card & window 11 host.

**Comment by raffaem** [comment]
@HH756 no sorry, I have switched to VirtualBox for the very rare times I need Windows
