### ISSUE TITLE
virt-install mis-setting driver type to raw when import qcow2

### ISSUE THREAD

**Issue by ryanjbudhu** [virt-manager/virt-manager#407]
**Distro**: Rocky Linux 8.6

Description of problem:
when create kvm vm by importing the qcow2 base disk, it setup type raw to driver type

Version-Release number of selected component (if applicable):
```
# virt-install --version`
3.2.0
```
Repo:
`virt-install-3.2.0-4.el8.noarch (libvirt-client-8.0.0-5.module+el8.6.0+847+b490afdd.x86_64)`

How reproducible:

Steps to Reproduce:
1.generate qcow2 base image by virt-builder 

```
# virt-builder centos-8.6 \
--format qcow2 \
--size 20G -o /path/to/centos-8.6-20G.qcow2
```

2.copy base image disk to vm disk

`cp /path/to/centos-8.6-20G.qcow2 /path/to/testvm.qcow2`

3.create vm testvm by importing qcow2 base disk, 
```
# virt-install --import --name testvm2 \
--ram 1024 \
--vcpu 1 \
--disk path=/path/to/testvm.qcow2,device=disk,format=qcow2 \
--nographics --serial=pty --os-type=linux --os-variant rocky8-unknown \
--noautoconsole --noreboot
```
Actual results:
the testvm driver type is raw instead of qcow2
```
 # virsh dumpxml testvm|grep driver
      <driver name='qemu' type='raw'/>
```
in this case, cannot start up vm

Expected results:
```
# virsh dumpxml testvm|grep driver
      <driver name='qemu' type='qcow2'/>
```
Additional info:

as remedy, change driver type to qcow2 then start up vm.
```
# virsh destroy testvm
# virsh edit testvm
# virsh start testvm
```

`virt-install --debug` log and `qemu-img info` is attached.
[libvirt bug.txt](https://github.com/virt-manager/virt-manager/files/8977725/libvirt.bug.txt)

**Comment by crobinso** [comment]
As mentioned in the issue template, since you are using an old distro version of virt-install, you'll need to file a bug with your distro. Or reproduce this using virt-install from git

**Comment by fillest** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1661683

**Comment by hw-claudio** [comment]
@crobinso  this seems to be still a bug in latest virt-install, still hitting it.

**Comment by crobinso** [comment]
@hw-claudio thanks for letting me know, I can't reproduce this with .git. can you file a new issue, with full `virt-install --debug` output, and `qemu-img info` output of the affected file?

Note, you can use `--print-xml` to skip any VM creation and just dump the generated XML, which will simplify reproducing

**Comment by crobinso** [comment]
@hw-claudio actually there's a newer issue filed, maybe follow up there: https://github.com/virt-manager/virt-manager/issues/407#top

**Comment by crobinso** [comment]
hmm maybe that issue isn't exactly the same, could be same root cause though

**Comment by hw-claudio** [comment]
@crobinso partly related, I think that the way virt-install deals with disks, especially when in presence of --print-xml, --dry-run is fundamentally very limiting.

It should be possible to use virt-install to generate the desired xml independently on whether the disks are available and reachable at the time of the xml generation.

For example for automated large scale conversions of VMWare .vmx to libvirt .xml it is very convenient to be able to separate the task of generating the xml from the task of efficient VMDK to QCOW2 image conversion, instead of having to generate the QCOW2 first, before being able to get the xml .

All the checks in virt-install that assume that the referenced disks exist should not be there if running under --print-xml.

But probably this use was not considered when writing virt-install.

Reference: https://gitlab.suse.de/virtualization/vmx2xml

**Comment by crobinso** [comment]
@hw-claudio OK interesting. can you file a new issue so we can discuss further? the main reason we still require storage to exist is so we can reuse libvirt machinery to determine image format, and file vs block vs dir, possibly others. but there's definitely a case to make that optional, or smart enough to skip it automatically if user specifies all the data for --print-xml, etc.

**Comment by hw-claudio** [comment]
ah btw sorry I send the wrong link: https://github.com/hw-claudio/vmx2xml

Here I am playing with Vmware .vmx to xml automated conversions
