### ISSUE TITLE
Unexpected cancelling of installation after closing out of "Customise configuration before install"

### ISSUE THREAD

**Issue by donefool** [virt-manager/virt-manager#416]
**Distro**: Fedora 36

After New VM -> Customise configuration before install -> Finish  the close button does not behave as you may expect it to. Instead of going back to the previous screen that says "Ready to begin the installation" it cancels the installation entirely. It also does not bring up an abort prompt which is odd considering the "Cancel Installation" in the top-left corner does, which you may not see when you do this for the first time. Not a massive issue, just an inconvenience which happened to me a few times when I first used virt manager

**Comment by crobinso** [comment]
Thanks for the report, indeed the window should not have been had the window manager X exit option, I've removed that now. That's the only practical way. This forces users to use the Cancel button, which notifies that the installation will be exited. 

Unfortunately due to the way things are structured internally, it's not currently feasible to drop back to the New VM wizard
