### ISSUE TITLE
virt-manager with wifi bridge

### ISSUE THREAD

**Issue by Kandrese** [virt-manager/virt-manager#427]
I have noticed that bridging with Wifi is currently complicated due to the wifi access points AP normally rejecting frames that have a source address that did not authenticate with the AP. Several solutions for this exist; Debian mention "ebtables" <https://wiki.debian.org/BridgeNetworkConnections#Bridging_with_a_wireless_NIC> Arch mention iptables-nfs <https://forum.manjaro.org/t/replacing-ebtables-by-iptables-nft-in-virt-managers-wiki-page/85547>

virtualbox, which also is under GPL does have wifi-bridging for guest os'es built in already. (I can mention that my router list these guest connected by virtual wifi as if connected by lan cable, but thats ok as long as it is working)

I myself am not sure which solution is best; I am on Debian 11, and am for now trying to get ebtables to work with my virt-manager. 

If anyone have working setup that make this transparent like in virtualbox I would be happy; regardless I hope this get merged into the virt-manager by default soon!

**Comment by crobinso** [comment]
Thanks for the report but this is outside scope for virt-manager.

If virt-manager wanted to provide any option to make wifi cards work in a bridge like mode, it would need to be something that was supported easily and natively in libvirt, like some kind of virtual network object that makes this 'just work'. If that existed, we would advertise it in the UI. But it doesn't exist, and I know of no plans to make it happen, so I'm closing this issue since there's nothing to track.

My understanding is virtualbox has special kernel drivers for some of its networking modes, but I've never looked into the details. Even if virt-manager wanted to use them though, it would start with adding support in libvirt.
