### ISSUE TITLE
XML produced by "--filesystem ..." sometimes fails to validate

### ISSUE THREAD

**Issue by Toolybird** [virt-manager/virt-manager#437]
**Distro**: Arch Linux (but I'm using latest virt-manager trunk)

Steps to reproduce:
```
$ virt-install --osinfo linux2022 --disk none --filesystem "/tmp,host,driver.type=virtiofs" --print-xml > /tmp/foo.xml
$ virt-xml-validate /tmp/foo.xml
Relax-NG validity error : Extra element devices in interleave
/tmp/foo.xml:31: element devices: Relax-NG validity error : Element domain failed to validate content
/tmp/foo.xml fails to validate
```

It's a minor thing and I only noticed it because I tend to add "--validate" to "virsh define ...". The problem is an ordering issue:
```
    <filesystem type="mount">
      <source dir="/tmp"/>
      <target dir="host"/>
      <driver type="virtiofs"/>
    </filesystem>
```
If "driver" is moved above "source" it validates successfully.

**Comment by crobinso** [comment]
Thanks for the report, but what version of libvirt is this? I think libvirt 7.0.0 relaxed the schema to not warn about this. Libvirt doesn't care about element ordering.

https://gitlab.com/libvirt/libvirt/-/commit/1dd607cd9cc1af35415fd15e24d1761214db6d09

**Comment by Toolybird** [comment]
> what version of libvirt is this?

Latest. Re-tested just now with libvirt-8.8.0 and can still repro. Maybe it's a libvirt bug?

**Comment by crobinso** [comment]
Hmm indeed, I reproduced with libvirt.git now. I couldn't fix the schema in 5 mins of trying, so let's move this to upstream libvirt tracker. We can fix XML generation on the virt-install side but it's not going to fix things with `virt-xml --edit` or manual `virsh edit`, so ultimately I think this should be fixed in libvirt.

Can you file a bug against libvirt? https://gitlab.com/libvirt/libvirt/-/issues
