### ISSUE TITLE
RFE: use `virt-ssh-helper` instead of `nc`, if available

### ISSUE THREAD

**Issue by antipatico** [virt-manager/virt-manager#439]
**Host Distro (running libvirtd)**: Arch Linux
**Guest Distro (running virt-manager)**: Ubuntu 20.04

When trying to **remotely connect** to my hypervisor, I get this error:

```
Unable to connect to libvirt qemu+ssh://antipatico@192.168.1.2/system.

End of file while reading data: sh: line 1: nc: command not found: Input/output error

Verify that the 'libvirtd' daemon is running on the remote host.

Libvirt URI is: qemu+ssh://antipatico@bimbo.lan/system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 956, in _do_open
    self._backend.open(connectauth.creds_dialog, self)
  File "/usr/share/virt-manager/virtinst/connection.py", line 172, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib/python3/dist-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: End of file while reading data: sh: line 1: nc: command not found: Input/output error

```

I know I am not running the upstream github version, as described by the Contribution guideline, but I checked and [it seems like it is also required in the upstream version](https://github.com/virt-manager/virt-manager/blob/8377b7f7b69ed0716fbe2c2818979a273bcb7567/virtManager/lib/connectauth.py#L154)

There are two bugs concerning this:
1. The [regex which should match the netcat error does not match](https://github.com/virt-manager/virt-manager/blob/8377b7f7b69ed0716fbe2c2818979a273bcb7567/virtManager/lib/connectauth.py) resulting in an erroneous error message.
2. The requirement for netcat to be installed on the host seems avoidable, in my humble opinion. Is there anyone who could explain to me why it is required and what is the work to be done to be removed? I am looking forward to fix this bug.

Thanks for your time

**Comment by crobinso** [comment]
That error actually comes from libvirt. Connecting to remote qemu+ssh URIs historically required `nc` installed on the host, since we use `nc -U /path/to/libvirt/socket` to stream the socket communication back over ssh, to talk to the libvirtd daemon on the remote host.

Nowadays libvirt has its own helper for that, virt-ssh-helper, so on newer distros you won't see that error anymore.

However, virt-manager still will attempt to use `nc` on its own, when connecting to graphical consoles for VMs hosted on remote machines over ssh connections. We should investigate using `virt-ssh-helper` for those cases if possible. Repurposing this bug for that

**Comment by jfehlig** [comment]
AFAICT, virt-ssh-helper only supports relaying to unix domain sockets. It will need enhanced to support network sockets/ports before virt-manager could use it for tunneling VM graphical consoles.

**Comment by crobinso** [comment]
@jfehlig hmm good point, I didn't realize that. probably doesn't make sense for virt-manager's usecase then. closing this one.
