### ISSUE TITLE
more comprehensive tool panel for full-screen viewing

### ISSUE THREAD

**Issue by brainchild0** [virt-manager/virt-manager#450]
# Request

Presently, full-screen mode features a hidden panel with two buttons, one for ending full screen mode and another for accessing special key combinations.

Virt-viewer has a further button in the analogous panel, also useful, for managing USB devices.

Proposed is adding a button for USB devices, but also, and of even greater practical use, buttons for minimizing (without restoring to a window), for taking screenshots,  and for life-cycle operations such as reset and shutdown.

# Environment

**Operating system:** Linux Mint 21
**Application version:** 4.0.0

**Comment by crobinso** [comment]
Thanks for the suggestion. But since virt-viewer already provides those features, IMO I'm fine with saying that if you need them, just use virt-viewer, which is superior anyways for regular fullscreen usage. virt-manager does not aim to cover all the use cases that virt-viewer does, just common workflows.
