### ISSUE TITLE
virt-manager and gpg-key for ssh auth

### ISSUE THREAD

**Issue by thomascriscione** [virt-manager/virt-manager#48]
Hello team,

I use a ssh connection with a gpg key to connect to my host.

However when I try to connect virt-manager to my host with:

`virt-manager -c 'qemu+ssh://vlp@myhost.tld/system?socket=/var/run/libvirt/libvirt-sock'`

virt-manager use by default the private ./ssh/id_rsa. I know that I can specify an other private key by adding &keyfile=~/id_rsa but I would like virt-manager to use gpg-agent just like my ssh connections.

**Comment by crobinso** [comment]
Hi, thanks for the suggestion. All virt-manager does is pass that URI off to libvirt to handle the connection, so your request belongs there. However all libvirt really does is invoke 'ssh', so whatever ssh will do by default is what you get. And I don't think libvirt project will want to make the behavior here any more complicated as it has been largely unchanged for a decade.

Maybe there's some way you can set host specific config in .ssh/config to have it try and use gpg-agent automatically for any 'ssh' invocation?

**Comment by AverageHumanoid** [comment]
Hey I just encounted a similar problem and found this post from Googling. Basically I just finished setting up SSH to using my GPG key and am able to connect to a remote system no problem with `root@remotehost` or `virsh --connect qemu+ssh://root@remotehost/system` but `virt-manager` was unable to connect. Eventually I noticed `virt-manager` was able to connect if I launched it from the terminal instead of app launcher so I copied `/usr/share/applications/virt-manager.desktop` to `$HOME/.local/share/applications/virt-manager.desktop` and changed `Exec=virt-manager` to `Exec=env SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh virt-manager`. Hope this can help someone else in the future.

**Comment by MexHigh** [comment]
I have this problem, too. When connecting to the host via "normal" SSH, it works and SSH uses gpg-agent. I already use the SSH config file for this. But Virt-manager cannot use gpg-agent for some reason...

**Comment by ossimoi** [comment]
SSH access with GPG key works as expected when virt-manager is started from terminal and env vars GPG_TTY and SSH_AUTH_SOCK are passed to the process. Process does not have access to these vars when started via .desktop file.

**Comment by desyncit** [comment]
This works for me. 
```
% awk '/Exec/' /usr/share/applications/virt-manager.desktop
Exec=SSH_AUTH_SOCK=/run/user/$(id -u)/gnupg/S.gpg-agent.ssh virt-manager
```
