### ISSUE TITLE
`--cloud-init` + `--events on_reboot=restart` and the VM still fully shuts down after VM initiated reboot

### ISSUE THREAD

**Issue by lebfr** [virt-manager/virt-manager#497]
**Distro**: Debian 11
**Version**:  3.2.0

Steps:
virt-install --events on_reboot=restart \
--name test2 --memory 2048 --vcpus 1 --cpu host \
--os-type=linux --os-variant debian10 \
--import --disk vol=default/test2.qcow2 \
--network network=lan,model=virtio \
--graphics vnc \
--cloud-init disable=on,meta-data=/vm/templates/test2-meta-data,user-data=/vm/templates/user-data \
--noautoconsole \
--autostart

Expected result:
virsh dumpxml test2 | grep on_reboot
  <on_reboot>restart</on_reboot>

Actual result:
virsh dumpxml test2 | grep on_reboot
  <on_reboot>destroy</on_reboot>

[This code](https://github.com/virt-manager/virt-manager/blob/33ff193ee9fcfdb74f95d946a1b93239a1a12a61/virtinst/install/installer.py#L237) is always executed. The virtual machine always shutdown on the first reboot. The --events option does not affect the behavior. It is not always comfortable when importing a virtual machine.

**Comment by lebfr** [comment]
I changed the behavior for myself but my code looks like a very dirty hack.

**Comment by lebfr** [comment]
https://github.com/lebfr/virt-manager/commit/6a386f3939dc3872c7ffe50330967cce1c747f03

**Comment by kettlewell** [comment]
Thanks for the code... I can vouch that in my use case, it works as intended... I've been pulling my hair out trying to figure out why virt-install wasn't rebooting when cloud-init was setting the reboot mode in the power_state... 

@lebfr were you going to create a PR for that, or was that just a starting point for someone else to run with?

**Comment by crobinso** [comment]
Sorry for late response. virt-install forcing shutdown is intended behavior. When you use `--cloud-init` we generate one time cloud-init media meant for initial VM configuration, and then we delete it. The only way to have the VM know that this is intended as one time media, is to force it to fully shut down, so we can change the VM config to remove the deleted media. New VM config can not be applied when VM does a warm reboot/reset.

Can yall explain what your usecase is? You want virt-install's generated cloud-init media to persist and retrigger for every boot? You want warm reboot for some usecase? Or is VM left in shutdown state but you want it running?

**Comment by kettlewell** [comment]
For my use case, I want a final reboot after cloud-init is done, so I leverage the power_state config similar to this:
```
power_state:
    delay: now
    mode: reboot
    message: Cloud Init Finalized - Rebooting machine
    condition: true
```

It's a way to prove to myself that I have a clean VM, and that cloud-init did as advertised, and the VM is now in-service, without any manual intervention.

The other choices I would have are to either 
a) manually restart the VM, or 
b) not power down, and assume that cloud-init is done and correct.

perhaps my use-case is rare, and not needed/useful, but the config options trail led me to believe it was possible, so maybe just a note somewhere for the `--cloud-init` option to warn that reboot isn't supported

based on what you're saying that the warm reboot/reset doesn't pickup a new VM config, I can now see ( with `lsblk -fa` ) that the cidata block device is still present, so there will need to be more thought behind this, if it is deemed a worthy use case to explore further.

**Comment by crobinso** [comment]
@kettlewell thanks for the info, I understand now. It helped refresh my memory.

This was actually an explicit change for --cloud-init. There's more info in the original issue: https://github.com/virt-manager/virt-manager/issues/189

It's tough, because from outside the VM it's hard/impossible to know whether the guest initiated lifecycle change was from a `reboot` or a `poweroff` (I believe qemu _does_ know but I don't think that's communicated to apps in any way I can find). So we can't really be smart here and force a poweroff so the new config takes effect, but then honor the original reboot request.

But by making `--cloud-init` not imply a reboot, we introduced the issue you see here, which is that guest initiated reboot is _never_ honored, and there's not any way around it with the virt-install cli itself, unlike the --noreboot option to opt out of `forced reboot` behavior for install media cases.

So I think we need to either go back on the `--cloud-init` change, or add a `--yesreboot` option to go opposite the `--noreboot`.

In the meantime, as a workaround you can largely get the behavior you want by doing ``virt-install ... --wait && sleep 5 && virsh start $VMNAME` or similar.
