### ISSUE TITLE
Cannot create VM that save on external hard drive

### ISSUE THREAD

**Issue by github2099** [virt-manager/virt-manager#513]
Host: Pop!_OS 22.04
Kernel: 6.2.6
Virt-Manager: 4.0.0
libvirtd: 8.0.0

I tried to create a virtual machine (.qcow2) on an external hard drive.
But it returns an error: _The emulator may not have search permissions for the path: <path> Do you want to correct this now?_
I click yes
Another error: _Errors were encountered changing permissions for the following directories: <path> [Errno 1] Operation not permitted: <path> It is very likely the VM will fail to start up._
I click OK
Final error: _Unable to complete install: 'Cannot access storage file <path>' (as uid: 64055, gid:109): Permission denied'_

Note that, my external hard drive is LUKS encrypted.

**Comment by github2099** [comment]
If I run `sudo virt-manager`
I can then create virtual machine on external hard drive, or import .qcow2 file saved on external hard drive.

However, no matter how I start virt-manager, it will always run on qemu:///system

![Screenshot from 2023-04-27 06-06-32](https://user-images.githubusercontent.com/49584984/234831169-567e8775-c0b7-4495-85eb-77b7396b7996.png)

**Comment by phrdina** [comment]
So the issue here is that your external hdd is most likely mounted under `/run/medina/{username}/{somepath}` but the directory `/run/medina/{username}` on my system (Fedora) but on yours probably as well uses ACL instead of unix file permissions and virt-manager is not able to change ACL for that directory as your user doesn't have permissions to change it.

Current workaround for you is to fix the ACL every time you connect your external HDD manually using sudo or you can mount your external HDD using fstab.

**Comment by github2099** [comment]
thank you, I tried using `sudo virt-manager`
and it is working so far, will check on the permission settings
