### ISSUE TITLE
Update INSTALL.md regarding required software for ubuntu

### ISSUE THREAD

**Issue by EHJ-52n** [virt-manager/virt-manager#53]
I installed the following additional packages for building and running virt-manager under Ubuntu _18.04.3 LTS_: 

- `intltool`
- `python3-libvirt`
- `python3-libxml2`
- `python3-guestfs`

You might add it to the according section in the [INSTALL.md](../blob/master/INSTALL.md#pre-requisite-software).

Hope this helps.

**Comment by crobinso** [comment]
Thanks for the suggestion, but I'm not sure if I want to duplicate all build deps in the INSTALL.md file, which already has a link to the .spec file which is basically our canonical location of build dependencies. Especially because packages have different names on different distros. It quickly becomes a pain

I am closing this, but if you feel strongly feel free to send a PR and i'll take a look
