### ISSUE TITLE
Virtual Machine Manager: Unknown cause of dead space

### ISSUE THREAD

**Issue by davidhedlund** [virt-manager/virt-manager#552]
Ubuntu  18.04 and 20-04 has 10 px space
![image](https://github.com/virt-manager/virt-manager/assets/6416073/6ac2292a-5dea-422f-9f88-bb28366eadd6)

Ubuntu 22.04, and Ubuntu 23.10 has 30 px space
![image](https://github.com/virt-manager/virt-manager/assets/6416073/f197c0f7-f7e2-41b9-ac7a-27e3667c0ad1)

# Ubuntu 18.04
Full screen at 1440x900 does not add scroll bars.

![ubuntu_18 04-1440x900](https://github.com/virt-manager/virt-manager/assets/6416073/23d3205b-1693-406a-85fc-f6691469eb2e)

# Ubuntu 20.04 
Full screen at 1440x900 does not add scroll bars.

![ubuntu_20 04-1440x900](https://github.com/virt-manager/virt-manager/assets/6416073/a331a7e1-a307-49a3-b4f8-85d632c7babe)

# Ubuntu 22.04
Full screen at 1440x900 adds scroll bars.

![ubuntu_22 04-1440x900](https://github.com/virt-manager/virt-manager/assets/6416073/8422b6a7-e924-46ec-bea2-cd5d9825c6d8)

I have to lower the screen resolution to avoid the scroll bars:
![ubuntu_22 04-1280x854](https://github.com/virt-manager/virt-manager/assets/6416073/e702013d-7813-4f12-bf78-51b0bc968060)

# Ubuntu 23.10
Full screen at 1440x900 adds scroll bars.

![ubuntu_23 10-1440x900](https://github.com/virt-manager/virt-manager/assets/6416073/a63d6a04-b9fd-4ae5-9382-09a5a2acfde4)

I have to lower the screen resolution to avoid the scroll bars:
![ubuntu_23 10-1280x854](https://github.com/virt-manager/virt-manager/assets/6416073/ac90be35-1a4a-4e05-887a-1b7224a5b620)

**Distro**:
Ubuntu MATE 22.04
```
$ apt-cache show virt-manager
Package: virt-manager
Architecture: all
Version: 1:4.0.0-1
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Libvirt Maintainers <pkg-libvirt-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2298
Depends: gir1.2-gtk-3.0 (>= 3.10), gir1.2-gtk-vnc-2.0, gir1.2-gtksource-4, gir1.2-libosinfo-1.0, gir1.2-libvirt-glib-1.0, gir1.2-vte-2.91, python3-dbus, python3-gi (>= 3.31.3~), python3-gi-cairo, python3-libvirt (>= 0.7.1), virtinst (= 1:4.0.0-1), dconf-gsettings-backend | gsettings-backend, python3:any
Recommends: gir1.2-ayatanaappindicator3-0.1 | gir1.2-appindicator3-0.1, gir1.2-spiceclientglib-2.0, gir1.2-spiceclientgtk-3.0, libvirt-daemon-system (>= 1.2.7)
Suggests: gir1.2-secret-1, gnome-keyring, python3-guestfs, ssh-askpass, virt-viewer
Filename: pool/main/v/virt-manager/virt-manager_4.0.0-1_all.deb
SHA512: b6618d34087f2f5edb7fb19ce5b7e7fa151c4190b82ce5360b03050229837996d589af7965f5509c6a6570a605d17780733a57e9f4e76880cce8d4cf627fb0aa
Homepage: https://virt-manager.org/
Size: 261800
SHA256: 5f54b22d8dd4dd2db7e82f5267e72981699d97600a9ee56bfd98a6f2ea58538c
SHA1: 72b92481fcccaffaf2a947da85ae6f772ec8b258
MD5sum: 548c6d54a2aab650eb87db324a8ba502
```

**Comment by davidhedlund** [comment]
Self-reminder: convert this issue to a feature request by changing the title to "[Feature request] Setting to define space between the Virtual Machin Manager and the Virtual Machine screen"

**Comment by davidhedlund** [comment]
* https://github.com/virt-manager/virt-manager/issues/553

**Comment by phrdina** [comment]
This one took me longer then I expected to partially figure out.

Both Ubuntu 18.04 and 20.04 uses by default Xorg and everything is ok, but both 22.04 and 23.10 uses Wayland by default.
On the login screen if you click on some user and before actually typing password and hitting "enter" there is a wheel icon bottom right where you can pick "Ubuntu" and "Ubuntu Xorg" and selecting the Xorg version makes the screen displayed correctly without any scrollbar.

I also installed Ubuntu 20.04 and tried logging in using Wayland it worked correctly. I also tried installing Fedora 38 where Wayland is used by default and no issues there.

So my own personal testing with Ubuntu Mate 22.04:

| OS | Xorg | Wayland |
| :---: | :---: | :---: |
| Ubuntu 20.04 | OK | OK |
| Ubuntu 23.04 | OK | bad |
| Fedora 38 | OK | OK |

My best guess is that there is something happening with new Ubuntu on Wayland and most likely not related to virt-manager at all.

I tried Ubuntu 23.04 VM on Fedora 38 host as well and it seems that the issue happens only if the VM resolution is ****x900 or lower, it doesn't happen with resolutions that have higher height.

Since this is most likely not related to virt-manager at all I'm closing this issue.
