### ISSUE TITLE
FR: allow to start libvirt only just before launching virt-manager and stop it again automatically

### ISSUE THREAD

**Issue by firefoxlover** [virt-manager/virt-manager#611]
Fedora 39,
qemu, qemu-kvm, virt-manager

When enabling libvirtd.service it automatically starts with the system. This is quite a resource problem as it slows down everything and it makes no sense for certain use cases e.g. launching virt-manager

It would be great to have an option to just start libvirtd before actually using virt-manager. and stopping it again when virt-manager is closed.

starting is easy (user in libvirt group)

```
systemctl start libvirt
sleep 5
virt-manager &
```

But stopping would require listening to some dbus message or something? I am not sure about that.

and then

```
# listen to closed virt-manager
systemctl stop libvirt
```

**Comment by crobinso** [comment]
Fedora default is basically what you want: libvirtd is listening on a socket, when an app connects to it, libvirtd (well nowadays it's virtqemud) is started on demand. When virt-manager disconnects, the libvirt daemon shuts down after some period of inactivity.

The issue may be that you did `systemctl enable libvirtd.service`. Don't do that. Instead just enable all the `virt*d.socket` files (the fedora default)

virt-manager used to be in the service management game but it was too complicated to get correct, and things have gotten MORE complicated since then, so we aren't going back. If you want it to work in that very specific way, drop a wrapper in ~/bin/virt-manager that does what you want

**Comment by firefoxlover** [comment]
for anyone looking, this does the job:

```
socket_files=$(find /usr/lib/systemd/system -name 'virt*.socket')

for socket_file in $socket_files; do
    socket_name=$(basename "$socket_file")
    systemctl enable --now "$socket_name"
done
```
