### ISSUE TITLE
When  I am installing windows  or linux with virt-manage2.0,the VM is running very very slow?

### ISSUE THREAD

**Issue by feici03** [virt-manager/virt-manager#645]
**Distro**:

**Comment by phrdina** [comment]
Hi, can you please provide your host OS and if possible debug logs from virt-manager. You can run it from terminal using `virt-manager --debug`.

**Comment by timaeos** [comment]
For the record, I was also experiencing substantial slowdown when running in fullscreen mode with my settings. I think it was tied directly to my VM settings, however. Since the original poster didn't add details for their setup, here was mine:
[virt-manager-debug-240413.txt](https://github.com/virt-manager/virt-manager/files/14967666/virt-manager-debug-240413.txt)

What I found was that QXL in general was slower and had abysmal performance when in fullscreen mode. Switching Spice to Display Server Listen Type Address and the graphics driver to virtio improved performance. The reason I was looking into this was because Fedora KDE had a user report sluggish behaviour in their VMs after upgrading to Plasma 6 (Fedora 40). I tested a new VM in Gnome Boxes vs Virt-Manager and also found Gnome Boxes had better performance at first. After matching settings in virt-manager to what Gnome Boxes had in their settings, my performance in virt-manager essentially matched. 

I've forwarded the original poster to this post since after matching settings, I wasn't able to duplicate their performance issues.

Host Details:

Operating System: Fedora Linux 40 (KDE)
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.4-300.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 590 Series
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X470 AORUS GAMING 7 WIFI

![image](https://github.com/virt-manager/virt-manager/assets/104638316/1e16060f-f2d7-426c-bb7a-134a97d4f8bd)

**Comment by Germano0** [comment]
Same problem here as described by @timaeos 

Details of host machine running virt-manager 4.1.0:
- Fedora 40
- GPU: AMD Radeon RX480
- CPU: Ryzen 5 3600
- RAM: 128 GB
- kernel: 6.8.1-300.fc40.x86_64

[virt-manager_debug.txt](https://github.com/virt-manager/virt-manager/files/14967895/virt-manager_debug.txt)

**Comment by crobinso** [comment]
This bug is overloaded. If any one is still hitting issues, please open a new issue, provide the info requested in the issue template, and provide phridina's requested info if necessary
