### ISSUE TITLE
Inconsistent Console menu settings when VM is powered off and on again

### ISSUE THREAD

**Issue by grisu48** [virt-manager/virt-manager#658]
When a VM is being powered off while being in Serial terminal mode, the Console menu remains e.g. at "Serial 1" but once the machine is powered on again, the display is the Graphical Console.

Powering a VM off and on makes the menu option button inconsistent with the displayed console.

See the attached [demo screencast](https://github.com/virt-manager/virt-manager/assets/1527829/6ee48af0-f3d7-4b2a-b55b-1faa4d06b970) where I start a VM, switch to the Serial Console, turn the VM off, turn it on again and then you can see that the Menu is still in "Serial 1" but the displayed console is the Graphical one.

Would be great if the last setting gets remembered and then the corresponding console is being restored. Alternatively reset the Menu to the default settings at every startup.

**Distro**: openSUSE Tumbleweed

**Comment by phrdina** [comment]
Hi, thanks for the report. I did check current code and it is already fixed by this commit  014d1ef99b6bf1bd34050914fc3485395d6dd9ad . Once we have a new release and your distribution will pickup that release it will be fixed for you as well.

The new behavior will be more consistent:

- selected console is not saved so restarting virt-manager or closing the VM window will result in picking first console (graphical if available)
- shutting down the VM and starting it again will keep the last selected console unless you open the menu as loading the menu will reset the selected console to first console

This could be improved but with the limited resources we have for this project the current state makes it consistent and fixes this issue.

**Comment by grisu48** [comment]
Thank you, this is great! :+1:
