### ISSUE TITLE
USB redirection is messed up

### ISSUE THREAD

**Issue by FlailAway** [virt-manager/virt-manager#659]
**Mint+MATE-21.3 and 4.0 Virt-manager**: 

I don't know how to update my Distro 4.0 version to 4.1, but I I have read the change-log and this issue was not mentioned.

If I set "Spice USB redirection" in the virt-manager GUI to "Auto" it frequently behaves weirdly. I have a laptop (Intel-CPU) and have 3 identical VMs (Mint+MATE-21.3). This morning I had all 3 running, I went to #3, plugged in an Arduino (redirect set at auto) and everything locked up for that VM.

I went back to the Host and all is good, so I selected the #2 VM and it was good too. tried #3, still locked up. Went to the #1 VM and there was a redirect error message showing. I cleared that and went back to #3 and **now** all OK there with the Serial connection showing in the "Redirect USB device" window.

I have **never ** used the Arduino on the #1 VM, does not even have the IDE installed. 

I would really like to be able to use the redirect-auto as I am plugging and un-plugging the Arduino board maybe 100-times a day when developing stuff. That gets old fast having to popup the redirect window and click the checkbox. With it on Auto, this will happen up to 10-times a day with the Arduino board.

Is this likely to be fixed any time soon?

Thanks

**Comment by phrdina** [comment]
Hi, the auto usb redirection is handled by Spice that virt-manager uses internally. So this behavior you are describing could be related to Spice libraries on your host system. Not sure if we can do something about that from virt-manager side. I did try your scenario on my Fedora 39 with 3 different VMs using USB flash drive and it was always successfully redirected to VM that I had current focus. So if you have some OS with older versions it's possible this is already fixed in never versions.

To mitigate this issue for your current setup you can configure your VMs to list which USB devices are allowed to be redirected, there is no GUI in virt-manager for that so you will have to edit the VM XML directly. It is documented here https://libvirt.org/formatdomain.html#redirected-devices .

So in your case if you always use your Arduino with VM#3 figure out the vendor and product for your Arduino using `lsusb` while it is connected to host and forbit that device for VM#1 and VM#2 and allow it only for VM#3.
