### ISSUE TITLE
Top menu to minimize the VM and send keybinds dont show when hovered.

### ISSUE THREAD

**Issue by dhaneshdutta** [virt-manager/virt-manager#685]
used to work before, all of a sudden doesn't show the top menu of virt manager in a VM to minimize it on hover

**Comment by phrdina** [comment]
Do you mean the top menu when you switch to fullscreen view? Please provide your distribution including version, your graphical environment and what virt-manager version are you using. On Fedora 40 with i3 it works.

**Comment by 1player** [comment]
I have this problem because since I installed the SPICE guest tools, when I fullscreen the display is ~1cm off the bottom of the screen (i.e. the guest window is offset, and there's a black bar at the bottom), so the top menu can't be reached because it's basically unreachable and off-screen.

This is GNOME/Wayland + 200% display scaling, and virt-manager has always been having issues with Wayland and/or scaling.

Pretty annoying, the workaround for me is never to go full-screen --- or never to install the SPICE guest tools with their auto-resolution feature which causes virt-manager to mess up when you go full-screen.
