### ISSUE TITLE
RFE: Make the ISO selection page for VM creation more clear/familiar

### ISSUE THREAD

**Issue by ddotthomas** [virt-manager/virt-manager#726]
I was helping someone install KVM and get virt-manager set up for the first time and they were finding the ISO selection screen a little confusing to use, and I remember it took some getting used to myself when I was learning to use virt-manager the first time. 

I'm wondering if everyone would find it agreeable if the locate ISO page was made to be a bit clearer and maybe just skip to the "Browse Local" option either everytime or if there aren't any recent ISOs from a previous folder. 

Furthermore, I would move that previous ISO folders list to be under the initial browse button and just make it a recent ISOs list instead independent of which folder they were in. 

So that way it's just a single empty path with a browse button, and underneath clicking on a recent ISO would fill it in the browse path above.

**Comment by phrdina** [comment]
The ISO selection is done this way for a reason. virt-manager can be used to manage VMs on local machine or on remote machine. On local machine `Browse Local` works but on remote machine it would not work. For that reason virt-manager uses storage pools in libvirt in order to manage storage on both local and remote machines.

The window after clicking on `Browse...` is not a list of previous ISO folders, that's a list of all storage pools. It's the same list as if you would click on `Edit -> Connection Details -> Storage`.

I understand that using storage pools is probably not that intuitive to first time users but I don't think we should change this to behave differently based on local or remote connection.
