### ISSUE TITLE
RPM Build fails due to Recommends tag

### ISSUE THREAD

**Issue by h1z1** [virt-manager/virt-manager#74]
Build fails due to the following commit which introduced tags not found in many RPM distros. 

https://github.com/virt-manager/virt-manager/blob/cf04920211eaff41ca074c0a06b12a7f6e34ae39/virt-manager.spec.in#L56

```
Creating tar archive
removing 'virt-manager-2.2.1' (and everything under it)
error: line 56: Unknown tag: Recommends: (libvirt-daemon-kvm or libvirt-daemon-qemu)
```

```
error: line 60: Unknown tag: Suggests: python3-libguestfs
```

Curios what version of RPM these tags were added because they most certainly do not exist in RHEL/CentOS7.

RPM v4.11.3

**Comment by crobinso** [comment]
Thanks for the report. Up until recently, rhel7 didn't even ship a version of python3 that was suitable for us to use, so when we ported to python3 we stripped out all rhel7 compat pieces and stopped considering it a supported target. At this stage I don't think we are going to change that even if it's more viably now.

If you just want to get things working, you can strip out those pieces from the spec, and try bumping down the gtksourceview RPM dependency to gtksourceview3. But there may be unknown runtime issues lurking

**Comment by h1z1** [comment]
It does indeed break because libvirt python bindings are also not python3.   Recompiling those turned into a whole other mess.  Why would RH do this?  I understand you are pushing cockpit or whatever it's called in RHEL8 but virt isn't going anywhere any time soon.

**Comment by crobinso** [comment]
Why are you talking about Red Hat like it's some amorphous blob moving in unison? The decision to drop RHEL7 support was largely made by me, acting in what I saw as the best interests of the virt-manager project given a bunch of different factors.

RHEL7.0 beta was released Dec 2013. At the time the latest python3 version was 3.3 and virtually no major python projects were ported to python3 in my experience. That's probably why RHEL7 decided not to ship a version of python3 in the regular repos but I don't know for sure. virt-manager upstream worked with RHEL7 for years, until in 2017 when we began porting the app to python3, as at that point there was growing momentum behind python3 ports, and python2 was approaching end of life. We finally released a python3 version in October 2018, and with that we dropped support for RHEL7. That's 4.5 years since the original RHEL7.0 GA release date.

RHEL7.7, released in August 2019, started shipping a python3 version. But at this point given the age of RHEL7 we are not going to add back support in virt-manager and all the testing and maintenance work that will entail.

All these decisions have literally nothing to do with RHEL8's decision to focus on cockpit as their recommended graphical management tool. virt-manager is supported in RHEL8 and I know of no plans to change that. cockpit also supports virt management so your statement `virt isn't going anywhere` is confusing

**Comment by h1z1** [comment]
> We finally released a python3 version in October 2018, and with that we dropped support for RHEL7. That's 4.5 years since the original RHEL7.0 GA release date.

I don't follow, just because something is released 4+ years ago doesn't mean it's bad. RHEL7 is not EOL until 2024 unless that has changed?   

> All these decisions have literally nothing to do with RHEL8's decision to focus on cockpit as their recommended graphical management tool. virt-manager is supported in RHEL8 

You dropped support in RHEL7 which will screw anyone who uses it.
