### ISSUE TITLE
Display notification when host shutdown while VMs are running

### ISSUE THREAD

**Issue by d1Bihkte** [virt-manager/virt-manager#766]
Please enhance the virt-manager to display system or software notification if user mistakenly shutdown / restart / logout host while VMs are running.

On ubuntu, if user shutdown / restart / logout while e.g. unsaved text editor (gnome-text-editor) file(s) is present, we can see a notification.

![Screenshot from 2024-11-18 09-10-26](https://github.com/user-attachments/assets/593c1d72-f0c4-4f2d-9fb9-51028a8c2f19)

**Comment by crobinso** [comment]
Thanks for the suggestion. This is a bit weird though because virt-manager doesn't really `own` your VMs or anything. You could start a VM, close virt-manager, VM is still running but you wouldn't get any desktop warning. And there's not any clear notion of `unsaved work` for using a VM.

Libvirt already registers with systemd to delay shutdown if VMs are running. I'm not quite sure where that pops up though? Maybe gnome could consume that info and display it to users.

I don't think we are going to change anything here though
