### ISSUE TITLE
Virt-Manager vector logo .svg

### ISSUE THREAD

**Issue by joniant** [virt-manager/virt-manager#768]
![virt-manager](https://github.com/user-attachments/assets/df11201c-ca3f-4cda-b15b-33c0617ed2be)

**Comment by crobinso** [comment]
@joniant sent this to me in private mail, it's an .svg version of the log, since all we have are .png files. I asked him to submit an issue so it's documented somewhere. I don't know if it makes sense to commit to git since we don't have any specific usage for it in the code, but it might be useful in the future. Thanks @joniant!
