### ISSUE TITLE
Change Emulator

### ISSUE THREAD

**Issue by aamlani** [virt-manager/virt-manager#85]
Hi, it seems virt-manager defaults to the emulator in /usr/libexec. I'd like to point it to one located in /usr/local/bin. How can I do that?

**Comment by crobinso** [comment]
virt-manager gets that information from libvirt capabilities output, like `virsh capabilities`. If you put in /usr/local/bin in your system PATH the emulator might show up in capabilities. But there's no designated way to change the default advertised path. You could try destructive things like overwriting the /usr/libexec or uninstalling the /usr/libexec binary, but it may destroy your system so that's up to you
