### ISSUE TITLE
Need a hotkey to switch between fullscreen and window mode

### ISSUE THREAD

**Issue by a188037445** [virt-manager/virt-manager#91]
thx.

**Comment by crobinso** [comment]
The problem with a hot key for fullscreen mode is that then the key can't be passed to the guest. So if you use standard F11, you can use it to get into Fullscreen mode, but then if it is also wired to unfullscreen, F11 can't be used by the VM. virt-viewer uses F11 to get into fullscreen but seems to disable it for getting out of fullscreen. We could do something similar in virt-manager but I'd want to make it a ctrl+combo at least. It's not a priority to track though, we've gotten this far without anything like that

**Comment by udopt** [comment]
I second this. What about a key combination using the right ctrl key, e.g. right ctrl + f? In that case the guest can still use the (probably more frequently used) left ctrl key and combinations such as left ctrl + f etc.

**Comment by tinywrkb** [comment]
What about hooking a fullscreen toggle action to dbus? the user could map the hotkey in the compositor (Wayland) to run a dbus-send command.  
This way you don't have to deal with the guest at all, the user just needs to disable the keyboard inhibitor in order for the hotkey to be sent to the host compositor, that's if it's not being filtered to always be sent to the host.

**Comment by tinywrkb** [comment]
Oh, and I guess this means virt manager needs to keep track of the currently active window.

**Comment by edbird** [comment]
Just to say I am another person who would appreciate such functionality, if it is possible to implement!

**Comment by maydayv7** [comment]
Me too!

**Comment by qkqsb** [comment]
Would love to see this feature

**Comment by gustavolens** [comment]
Yes, I would appreciate such feature too.

**Comment by RichardJECooke** [comment]
Why is this closed with no comment? We need this feature.

> The problem with a hot key for fullscreen mode is that then the key can't be passed to the guest. 

This is not true. You can just copy VirtualBox, where the key is configurable, but defaults to your escape combination (ctrl + alt is the default in virt-manager) + f.

**Comment by LeisureLinux** [comment]
those keyboard should can be customize. IMH

**Comment by MicioMax** [comment]
Using Ubuntu 23.04 now, but coming from all previous versions.
I've NO WAY to leave fullscreen mode once entered, I have to shut down my windows guest to do it.
I tried ALL, searched in internet, tried ALL suggestions, no way.
The icons on top doesn't appear, even pressing all ctrl, crtrl+alt, ctrl+f. ctrl-alt-f and so on. I tried also to change the hot key, nothing works.
Some years ago I was using virtualbox and then it was possible to leave fullscreen bu hotkey.
Why is it so difficult to implement for virt-manager too ?
Sometimes I press by mistake the full screen icon on top right and I have no access to my ubuntu desktop withiut shutting down windows guest. For me that's a serious usability problem.

**Comment by Boniewow** [comment]
Totaly agree after using virtual box 5-7 i really missing the hotkeys command function

**Comment by zmerch** [comment]
Came here having the same issue, and I do agree that there should be a configurable hot key for this function. Fought with this for far longer than I'd care to admit... but...

I think I figured out how to hop out of full screen without reboots. Like everyone else, I... "rammed" my mouse pointer to the center top of the window, and no little dropdown showed up to leave fullscreen. The issue is that at the very top of the screen, I think you're still in control of the OS and not virt-manager. What I did and it seems to work (albeit it's still a bit of a pain) is run your mouse pointer to the top center of the screen where you're running virt-manager, then slowly... sloowwwlly... move the mouse pointer down a pixel or two at a time and wait. There's a pause before the popup happens, so you can't just 'slide the mouse pointer up and down until it shows'  - you have to do this slowly with pauses. Once one gets accustomed to the timing it gets a lot easier to get to the popup, but it'll take a bit of practice. (Not sure if there's a better way to describe this... hope it makes sense.)

I hope this helps!

**Comment by antkowiak** [comment]
There is a fairly irritating UX problem here.  I realize this issue was closed, maybe perhaps because a keyboard hotkey/shortcut might not be the appropriate way to address it.

However...

My situation is:  I have two display monitors, which are stacked in a vertical layout.  (One display vertically above the other.)
I encounter the problem when I run a virtual machine in full-screen mode on the bottom/lower display.  It is almost impossible to get the little "pop-down-menu" to show up in order to un-full-screen the virtual machine.  Maybe the mouse-target-location is too small, or maybe it expects it to be exactly on the top-row of pixels of the display (which can be extremely difficult to do, if you have another physical display above it.)  Perhaps it also has something to do if the inputs are captured by the VM or not.  But in any case, I would love to see some sort of improvement that makes it easier to un-full-screen a vm (whether it is some sort of option that expands the mouse-target-area to activate the pop-down-area, or some menu item in the VirtualMachineManager that forces a vm out of full screen display.  Not sure if the improvement for this would need to be in QEMU or in VMM.

FWIW I'm using whatever versions that Ubuntu 24.04 LTS installs.  My Virtual Machine Manager says it is version 4.1.0.

Thanks to all the developers who work these projects.

**Comment by Roy-Orbison** [comment]
Given <kbd>Left Ctrl</kbd> + <kbd>Right Ctrl</kbd> is already used to 'escape' the VM by toggling keyboard capture, would it be possible to use something like <kbd>Left Ctrl</kbd> + <kbd>Right Ctrl</kbd> + <kbd>F</kbd>?

I'm still unable to exit full screen mode by only keyboard, because I can't get focus to the 🮻 exit button.
