### ISSUE TITLE
 Need help for compilation under Mint

### ISSUE THREAD

**Issue by dexter74** [virt-manager/virt-manager#96]
Hello,
I would like a little help on the compilation of your tools.

Your GIT and site lacks clear information on the compilation which I find its a shame.
On the other hand, if documentation could be created for Ubuntu, Debian and Mint.

As it stands, little useful information on the net and makes compilation difficult.

**Comment by crobinso** [comment]
I don't use mint so I can't give details on how to run virt-manager there. But I imagine package names are similar to ubuntu. Generally the steps to get it working on a distro is: install the distro version of the package with native tools (yum, apt, etc, virt-manager is usually there), and that typically installs all the dependencies you need. Then checkout virt-manager and just run `./virt-manager --debug` from the git checkout. If you hit errors you can ask about them here. I don't generally aim to have the INSTALL docs track all possible distro package dependency names because it often goes out of date. I'll take patches to update the docs though

**Comment by dexter74** [comment]
Hello,


Would it be possible to let me answer before closing an incident, it's not super constructive
